### ISSUE TITLE
What is a dictionary in Stripe API?

### ISSUE THREAD

**Issue by eric-brechemier** [eGullGolf/stripe-shell#1]
For example, the [List all charges API](https://stripe.com/docs/api#list_charges) mentions that `created` is an optional dictionary with child arguments `gt`, `gte`, ` lt`, `lte`, and returns "A dictionary with a data property".

**Comment by greguly** [comment]
Thank you for this.

**Comment by JonShaltz-Idera** [comment]
I appreciate you taking a moment to make this clear.  I was pulling my hair out trying to find the magic syntax that would please the API, as [the example given](https://stripe.com/docs/api/invoices/list?lang=cli) just showed a simple parameter, and the error messages returned were not specific enough to be helpful.
