### ISSUE TITLE
Where can the Stripe Connect Client Id be found?

### ISSUE THREAD

**Issue by TimeGull** [eGullGolf/stripe-shell#2]
There is a parameter called `stripeConnectClientId` in the configuration file. What is its use and where can its value be found?

**Comment by eric-brechemier** [comment]
The identifier is found in Connect > Settings > Client IDs. It starts with the prefix `ca_`.

The live Client ID is called `Live mode client ID` while the test Client ID is called `Test mode client ID` and is displayed when "View test data" is toggled into "Viewing test data".

This is the identifier of the platform. It is included in the link to initiate the OAuth process to connect the platform account with a merchant's account:

```
https://dashboard.stripe.com/oauth/authorize?response_type=code&client_id=ca_...&scope=read_write
```

It is only used in endpoints related to OAuth:

* `oauth/authorize-url.sh`
* `oauth/deauthorize.sh`
* `accounts/activate-url.sh`

It is required for the above endpoints; it can safely be left empty when using all other endpoints.
